# Generated by Django 5.0.2 on 2025-04-13 19:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='guides/')),
                ('description', models.TextField()),
                ('experience_years', models.PositiveIntegerField()),
                ('languages', models.CharField(choices=[('EN', 'English'), ('FA', 'Farsi'), ('PS', 'Pashto'), ('AR', 'Arabic'), ('UR', 'Urdu')], default='EN', max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='guidereview',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='guides.guide'),
        ),
    ]
