# Generated by Django 5.0.2 on 2025-04-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0002_guide_alter_guidereview_guide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='languages',
            field=models.JSONField(default=list),
        ),
    ]
