# Generated by Django 5.0.2 on 2025-04-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0003_alter_guide_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='guides/'),
        ),
    ]
