# Generated by Django 5.0.2 on 2025-04-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0004_guide_is_active_alter_guide_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='guide',
            name='photo',
            field=models.ImageField(default='guides/guide_photos/default.jpg', upload_to='guides/guide_photos/'),
        ),
    ]
