# Generated by Django 5.0.2 on 2025-03-28 07:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='places/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_places', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='place',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_places', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='place',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(upload_to='places/', verbose_name='Main Image'),
        ),
        migrations.AddField(
            model_name='place',
            name='gallery',
            field=models.ManyToManyField(blank=True, to='main.placeimage'),
        ),
    ]
