# Generated by Django 5.0.2 on 2025-03-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_placeimage_place_favorites_place_likes_place_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='location_url',
            field=models.URLField(blank=True, help_text='URL to location on map', max_length=500),
        ),
    ]
