# Generated by Django 5.0.2 on 2025-04-15 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_favoriteimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guide',
        ),
    ]
