# Generated by Django 5.0.2 on 2025-04-16 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0002_transportationrental'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='transportation/')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='transportation.transportation')),
            ],
        ),
    ]
